Repository MicrosoftDocs/azure-docs.zh-cn, pull requests merged in 2018-12, with the labels that each got.

#196 Fix typo
  articles/cdn/cdn-rules-engine-reference-features.md
Labels: Accepted, Linguistic Suggestion

#186 Update quick-create-portal.md
  articles/virtual-machines/windows/quick-create-portal.md
Labels: Accepted, Linguistic Suggestion

#187 Update quick-create-powershell.md
  articles/virtual-machines/windows/quick-create-powershell.md
Labels: Accepted, Linguistic Suggestion

#191 Update concepts-collector-upgrade.md
  articles/migrate/concepts-collector-upgrade.md
Labels: Accepted, Linguistic Suggestion

#198 Update app-service-plan.md
  includes/app-service-plan.md
Labels: Accepted, Linguistic Suggestion

#202 Update app-service-web-get-started-nodejs.md
  articles/app-service/app-service-web-get-started-nodejs.md
Labels: Accepted, Linguistic Suggestion

#203 Update app-service-web-get-started-php.md
  articles/app-service/app-service-web-get-started-php.md
Labels: Accepted, Linguistic Suggestion

#197 Update index.yml
  articles/virtual-machines/linux/index.yml
Labels: In Progress, Linguistic Suggestion

#200 Update clean-up-section-portal-web-app.md
  includes/clean-up-section-portal-web-app.md
Labels: Accepted, Linguistic Suggestion

#194 Update app-service-web-get-started-php.md
  articles/app-service/app-service-web-get-started-php.md
Labels: Accepted, Linguistic Suggestion

#212 Update hdinsight-apps-install-applications.md
  articles/hdinsight/hdinsight-apps-install-applications.md
Labels: Accepted, Linguistic Suggestion

#205 Update azure-subscription-service-limits.md
  articles/azure-subscription-service-limits.md
Labels: Accepted, Linguistic Suggestion

#206 Update app-service-web-get-started-windows-container.md
  articles/app-service/app-service-web-get-started-windows-container.md
Labels: Accepted, Linguistic Suggestion

#175 “Contract" here in Chinese means "合约"
  articles/blockchain/workbench/integration-patterns.md
Labels: Accepted, Linguistic Suggestion

#179 Update active-directory-whatis.md
  articles/active-directory/fundamentals/active-directory-whatis.md
Labels: Accepted, Linguistic Suggestion

#213 Update app-service-web-get-started-dotnet.md
  articles/app-service/app-service-web-get-started-dotnet.md
Labels: Accepted, Linguistic Suggestion

#208 Update app-service-web-tutorial-dotnetcore-sqldb.md
  articles/app-service/app-service-web-tutorial-dotnetcore-sqldb.md
Labels: In Progress, Linguistic Suggestion

#210 Update app-service-web-tutorial-nodejs-mongodb-app.md
  articles/app-service/app-service-web-tutorial-nodejs-mongodb-app.md
Labels: In Progress, Linguistic Suggestion

#215 Update quick-create-cli.md
  articles/virtual-machines/linux/quick-create-cli.md
Labels: Accepted, Linguistic Suggestion

#199 Update app-service-web-get-started-java.md
  articles/app-service/app-service-web-get-started-java.md
Labels: In Progress, Linguistic Suggestion

#207 Update azure-developer-guide.md
  articles/guides/developer/azure-developer-guide.md
Labels: Accepted, Linguistic Suggestion

#195 Update app-service-web-git-push-to-azure-no-h.md
  includes/app-service-web-git-push-to-azure-no-h.md
Labels: Accepted, Linguistic Suggestion

#201 Update app-service-web-get-started-html.md
  articles/app-service/app-service-web-get-started-html.md
Labels: Accepted, Linguistic Suggestion

#214 Update overview.md
  articles/virtual-machines/linux/overview.md
Labels: Accepted, Linguistic Suggestion

#216 Update tutorial-manage-disks.md
  articles/virtual-machines/linux/tutorial-manage-disks.md
Labels: Accepted, Linguistic Suggestion

#223 Update walkthrough-2-upload-data.md
  articles/machine-learning/studio/walkthrough-2-upload-data.md
Labels: Accepted, Linguistic Suggestion

#217 Update what-is-ml-studio.md
  articles/machine-learning/studio/what-is-ml-studio.md
Labels: In Progress, Linguistic Suggestion

#221 Update create-experiment.md
  articles/machine-learning/studio/create-experiment.md
Labels: Linguistic Suggestion

#220 Update faq.md
  articles/machine-learning/studio/faq.md
Labels: Linguistic Suggestion

#219 Update basics-infographic-with-algorithm-examples.md
  articles/machine-learning/studio/basics-infographic-with-algorithm-examples.md
Labels: Accepted, Linguistic Suggestion

#224 Update walkthrough-3-create-new-experiment.md
  articles/machine-learning/studio/walkthrough-3-create-new-experiment.md
Labels: In Progress, Linguistic Suggestion

#222 Update walkthrough-1-create-ml-workspace.md
  articles/machine-learning/studio/walkthrough-1-create-ml-workspace.md
Labels: In Progress, Linguistic Suggestion

#228 Update container-registry-auth-aci.md
  articles/container-registry/container-registry-auth-aci.md
Labels: In Progress, Linguistic Suggestion

#231 Update container-registry-authentication.md
  articles/container-registry/container-registry-authentication.md
Labels: Accepted, Linguistic Suggestion

#234 Update app-service-web-tutorial-dotnet-sqldatabase.md
  articles/app-service/app-service-web-tutorial-dotnet-sqldatabase.md
Labels: Accepted, Linguistic Suggestion

#227 Update app-service-web-get-started-php.md
  articles/app-service/app-service-web-get-started-php.md
Labels: Accepted, Linguistic Suggestion

#243 Fix typo and fix indents and fix display collapse
  articles/cognitive-services/Content-Moderator/ecommerce-retail-catalog-moderation.md
Labels: Accepted, Linguistic Suggestion

#242 Update app-service-web-tutorial-dotnet-sqldatabase.md
  articles/app-service/app-service-web-tutorial-dotnet-sqldatabase.md
Labels: Accepted, Linguistic Suggestion

#233 Update what-is-single-sign-on.md
  articles/active-directory/manage-apps/what-is-single-sign-on.md
Labels: Accepted, Linguistic Suggestion

#240 Update tutorial-sspr-pilot.md
  articles/active-directory/authentication/tutorial-sspr-pilot.md
Labels: Accepted, Linguistic Suggestion
