Repository MicrosoftDocs/azure-docs.zh-cn, pull requests merged in 2019-04, with the labels that each got.

#381 Update virtual-machines-common-reserved-vm-instance-size-flexibility.md
  includes/virtual-machines-common-reserved-vm-instance-size-flexibility.md
Labels: Accepted

#379 Update concepts-clusters-workloads.md
  articles/aks/concepts-clusters-workloads.md
Labels: Linguistic Suggestion, Partially Accepted

#383 Update concept-sspr-howitworks.md
  articles/active-directory/authentication/concept-sspr-howitworks.md
Labels: In Progress

#387 Fix mistranslation
  articles/azure-monitor/platform/api-alerts.md
Labels: Accepted, In Progress

#386 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, In Progress

#385 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, In Progress

#384 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, In Progress

#393 Fix mistranslation
  articles/azure-monitor/platform/archive-diagnostic-logs.md
Labels: Accepted, In Progress, Linguistic Suggestion

#392 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress, Linguistic Suggestion

#391 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, In Progress, Linguistic Suggestion

#394 Fix mistranslation
  articles/azure-monitor/insights/wire-data.md
Labels: Accepted, In Progress, Linguistic Suggestion

#395 Fix mistranslation
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#396 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-insance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#397 Fix mistranslation
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, In Progress, Linguistic Suggestion

#399 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, In Progress

#398 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted, In Progress

#211 Update tutorial-nodejs-mongodb-app.md
  articles/app-service/containers/tutorial-nodejs-mongodb-app.md
Labels: Accepted, Linguistic Suggestion

#401 Fix mistranslation
  articles/azure-maps/geofence-geojson.md
Labels: Accepted, In Progress

#400 Fix mistranslation
  articles/api-management/api-management-product-templates.md
Labels: Accepted, In Progress

#402 Update links to Presto website
  articles/hdinsight/hdinsight-hadoop-install-presto.md
Labels: In Progress, Source Issue

#407 Fix mistranslation
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted, In Progress

#406 Fix mistranslation
  articles/automation/automation-solution-vm-management.md
Labels: Accepted, In Progress

#405 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, In Progress

#404 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#403 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, In Progress

#410 Fix mistranslation
  articles/api-management/api-management-howto-use-azure-monitor.md
Labels: Accepted, In Progress

#409 Fix mistranslation
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, In Progress

#408 Fix mistranslation
  articles/data-factory/control-flow-filter-activity.md
Labels: Accepted, In Progress

#414 Fix mistranslation
  articles/azure-monitor/insights/vminsights-log-search.md
Labels: Accepted, In Progress

#413 Fix mistranslation
  articles/data-factory/connector-web-table.md
Labels: Accepted, In Progress

#412 Fix mistranslation
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, In Progress

#411 Fix mistranslation
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, In Progress

#415 Fix mistranslation
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, In Progress
