Repository MicrosoftDocs/azure-docs.zh-cn, pull requests merged in 2019-05, with the labels that each got.

#421 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, In Progress

#422 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, In Progress

#423 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, In Progress

#424 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted, In Progress

#425 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, In Progress

#426 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted, In Progress

#428 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted, In Progress

#429 Fix mistranslation
  articles/data-factory/connector-cassandra.md
Labels: Accepted, In Progress

#430 Fix mistranslation
  articles/data-factory/connector-db2.md
Labels: Accepted, In Progress

#431 Fix mistranslation
  articles/data-factory/connector-dynamics-ax.md
Labels: Accepted, In Progress

#432 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted, In Progress

#433 Fix mistranslation
  articles/data-factory/connector-ftp.md
Labels: Accepted, In Progress

#434 Fix mistranslation
  articles/data-factory/connector-google-adwords.md
Labels: Accepted, In Progress

#435 Fix mistranslation
  articles/data-factory/connector-google-bigquery.md
Labels: Accepted, In Progress

#436 Fix mistranslation
  articles/data-factory/connector-google-cloud-storage.md
Labels: Accepted, Linguistic Suggestion

#437 Fix mistranslation
  articles/data-factory/connector-hdfs.md
Labels: Accepted, In Progress

#438 Fix mistranslation
  articles/data-factory/connector-http.md
Labels: Accepted, In Progress

#439 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, In Progress

#440 Fix mistranslation
  articles/data-factory/connector-odata.md
Labels: Accepted, In Progress

#441 Fix mistranslation
  articles/data-factory/connector-oracle.md
Labels: Accepted, In Progress

#444 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted, In Progress

#443 Fix mistranslation
  articles/data-factory/connector-presto.md
Labels: Accepted, In Progress

#445 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted, In Progress

#446 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted, In Progress

#447 Fix mistranslation
  articles/data-factory/connector-sap-cloud-for-customer.md
Labels: Accepted, In Progress

#448 Fix mistranslation
  articles/data-factory/connector-sap-ecc.md
Labels: Accepted, In Progress

#449 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, In Progress

#450 Fix mistranslation
  articles/data-factory/connector-sftp.md
Labels: Accepted, In Progress

#452 Update concepts-server-logs.md
  articles/postgresql/concepts-server-logs.md
Labels: In Progress, Linguistic Suggestion

#451 Update contoso-migration-rehost-vm-sql-ag.md
  articles/migrate/contoso-migration-rehost-vm-sql-ag.md
Labels: In Progress

#454 Fix mistranslation
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Linguistic Suggestion

#453 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted, Linguistic Suggestion

#455 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#456 Fix mistranslation
  articles/data-factory/monitor-using-azure-monitor.md
Labels: Accepted, Linguistic Suggestion

#457 Fix typo
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-rest-api.md
Labels: Accepted, In Progress

#460 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-rest-api.md
Labels: Accepted, In Progress

#462 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-visual-studio.md
Labels: Accepted, In Progress

#463 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, In Progress

#458 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-azure-portal.md
Labels: Accepted, In Progress

#461 Update howto-troubleshoot-common-connection-issues.md
  articles/postgresql/howto-troubleshoot-common-connection-issues.md
Labels: In Progress

#464 Update concepts-hyperscale-extensions.md
  articles/postgresql/concepts-hyperscale-extensions.md
Labels: Accepted, Linguistic Suggestion

#467 Fix mistranslation
  articles/data-factory/v1/data-factory-hdfs-connector.md
Labels: Accepted, Linguistic Suggestion

#466 Fix mistranslation
  articles/data-factory/v1/data-factory-ftp-connector.md
Labels: Accepted, Linguistic Suggestion

#465 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#468 Fix mistranslation
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted, Linguistic Suggestion

#469 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted, Linguistic Suggestion

#470 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#471 Fix mistranslation
  articles/data-factory/v1/data-factory-odata-connector.md
Labels: Accepted, Linguistic Suggestion

#472 Fix mistranslation
  articles/data-factory/v1/data-factory-odbc-connector.md
Labels: Accepted, Linguistic Suggestion

#473 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, In Progress

#474 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-file-system-connector.md
Labels: Accepted, In Progress

#475 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted, In Progress
