Repository MicrosoftDocs/azure-docs.zh-cn, pull requests merged in 2019-06, with the labels that each got.

#479 Fix mistranslation
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: Accepted

#477 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#478 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#476 Update concept-detecting-domain-content.md
  articles/cognitive-services/Computer-vision/concept-detecting-domain-content.md
Labels: In Progress, Linguistic Suggestion

#481 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted, Linguistic Suggestion

#482 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#483 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#480 Update HowToCallVisionAPI.md
  articles/cognitive-services/Computer-vision/Vision-API-How-to-Topics/HowToCallVisionAPI.md
Labels: Accepted, Linguistic Suggestion

#487 Fix mistranslation
  articles/data-factory/v1/data-factory-stored-proc-activity.md
Labels: Accepted, Linguistic Suggestion

#486 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#485 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted, Linguistic Suggestion

#492 Fix mistranslation
  articles/event-grid/event-schema-container-registry.md
Labels: Accepted, Linguistic Suggestion

#491 Fix mistranslation
  articles/event-grid/event-schema-blob-storage.md
Labels: Accepted, Linguistic Suggestion

#490 Fix mistranslation
  articles/event-grid/event-schema-azure-maps.md
Labels: Accepted, Linguistic Suggestion

#489 Fix mistranslation
  articles/digital-twins/how-to-egress-endpoints.md
Labels: Accepted, Linguistic Suggestion

#496 Fix mistranslation
  articles/event-grid/event-schema-service-bus.md
Labels: In Progress

#495 Fix mistranslation
  articles/event-grid/event-schema-resource-groups.md
Labels: In Progress

#494 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: In Progress

#493 Fix mistranslation
  articles/event-grid/event-schema-event-hubs.md
Labels: In Progress

#500 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#499 Fix mistranslation
  articles/event-grid/subscription-creation-schema.md
Labels: In Progress

#498 Fix mistranslation
  articles/event-grid/event-schema.md
Labels: In Progress

#497 Fix mistranslation
  articles/event-grid/event-schema-subscriptions.md
Labels: In Progress

#501 Fix mistranslation
  articles/load-balancer/create-load-balancer-rest-api.md
Labels: In Progress

#502 Fix mistranslation
  articles/logic-apps/logic-apps-custom-api-authentication.md
Labels: In Progress

#503 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#504 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-as2-tracking-schemas.md
Labels: In Progress

#505 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#509 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-x12-tracking-schema.md
Labels: In Progress

#510 Fix mistranslation
  articles/managed-applications/create-uidefinition-elements.md
Labels: In Progress

#511 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#513 Fix mistranslation
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension.md
Labels: In Progress

#512 Fix mistranslation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: In Progress

#508 Update cognitive-services-containers-configuration-shared-settings-ta…
  includes/cognitive-services-containers-configuration-shared-settings-table.md
Labels: In Progress, Linguistic Suggestion

#506 fix wrong translation
  articles/blockchain/service/overview.md
Labels: Accepted, Linguistic Suggestion

#516 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-windows.md
Labels: In Progress

#515 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-linux.md
Labels: In Progress

#514 Fix mistranslation
  articles/service-fabric/service-fabric-cluster-nodetypes.md
Labels: In Progress

#518 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-windows.md
Labels: In Progress

#520 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: In Progress

#523 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linuxOstc.md
Labels: Accepted

#526 Fix mistranslation
  articles/virtual-machines/extensions/dsc-template.md
Labels: Accepted, Linguistic Suggestion

#527 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted, Linguistic Suggestion

#528 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-linux.md
Labels: Accepted, Linguistic Suggestion

#524 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-windows.md
Labels: Accepted, Linguistic Suggestion

#529 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-windows.md
Labels: In Progress

#531 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/BingVoiceOutput.md
Labels: In Progress

#530 Fix mistranslation
  articles/virtual-machines/extensions/oms-windows.md
Labels: In Progress

#519 Fix mistranslation
  articles/virtual-machines/extensions/chef.md
Labels: Accepted, Linguistic Suggestion

#534 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: In Progress

#533 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: In Progress

#540 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#536 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: In Progress

#537 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: In Progress

#539 Fix mistranslation
  articles/data-factory/control-flow-if-condition-activity.md
Labels: In Progress

#535 Update text-to-speech.md
  articles/cognitive-services/Speech-Service/text-to-speech.md
Labels: Accepted, Linguistic Suggestion

#544 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#543 Update language-support.md
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted

#545 Fix mistranslation
  articles/media-services/latest/media-services-event-schemas.md
Labels: Accepted

#517 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: Accepted, Linguistic Suggestion

#547 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#548 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted, Linguistic Suggestion

#551 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#550 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#552 Fix mistranslation
  articles/azure-monitor/insights/solutions-solution-file.md
Labels: Accepted, Linguistic Suggestion

#549 Update how-to-custom-speech-human-labeled-transcriptions.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech-human-labeled-transcriptions.md
Labels: In Progress

#554 Fix mistranslation
  articles/azure-monitor/log-query/unify-app-resource-data.md
Labels: Accepted

#555 Fix mistranslation
  articles/azure-monitor/platform/activity-log-export.md
Labels: Accepted

#556 Fix mistranslation
  articles/azure-monitor/platform/alerts-webhooks.md
Labels: Accepted

#557 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#553 Update stream-analytics-javascript-user-defined-functions.md
  articles/stream-analytics/stream-analytics-javascript-user-defined-functions.md
Labels: In Progress
