Repository MicrosoftDocs/azure-docs.zh-cn, pull requests merged in 2019-01, with the labels that each got.

#248 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, Technical Issue

#247 Translation translation omission
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Technical Issue

#249 Fix overtranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: Accepted, Linguistic Suggestion

#250 Fix overtranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#251 Fix mistake
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, Linguistic Suggestion

#256 Translation translation omission
  articles/azure-functions/functions-host-json.md
Labels: Accepted, Technical Issue

#255 Translation translation omission
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Technical Issue

#254 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb.md
Labels: Accepted, Technical Issue

#253 Translation translation omission
  articles/data-factory/tutorial-copy-data-tool.md
Labels: Accepted, Technical Issue

#252 Translation translation omission
  articles/data-factory/concepts-pipeline-execution-triggers.md
Labels: Accepted, Technical Issue

#259 Translation translation omission
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, Technical Issue

#258 Translation translation omission
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, Technical Issue

#257 Translation translation omission
  articles/data-factory/concepts-datasets-linked-services.md
Labels: Accepted, Technical Issue

#261 Translation translation omission
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, Technical Issue

#262 Translation translation omission
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted, Technical Issue

#263 Translation translation omission
  articles/data-factory/connector-azure-search.md
Labels: Accepted, Technical Issue

#264 Translation translation omission
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, Technical Issue

#265 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-copy-data-tool.md
Labels: Accepted, Technical Issue

#266 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-portal.md
Labels: Accepted, Technical Issue

#273 Translation translation omission
  articles/media-services/previous/media-services-overview.md
Labels: Accepted, Technical Issue

#272 Translation translation omission
  articles/media-services/previous/media-services-media-encoder-standard-formats.md
Labels: Accepted, Technical Issue

#271 Translation translation omission
  articles/data-factory/introduction.md
Labels: Accepted, Technical Issue

#270 Translation translation omission
  articles/data-factory/control-flow-expression-language-functions.md
Labels: Accepted, Technical Issue

#269 Translation translation omission
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Technical Issue

#268 Translation translation omission
  articles/data-factory/copy-activity-performance.md
Labels: Accepted, Technical Issue

#267 Translation translation omission
  articles/data-factory/copy-activity-fault-tolerance.md
Labels: Accepted, Technical Issue

#275 Translation translation omission
  articles/data-factory/v1/data-factory-sap-hana-connector.md
Labels: Accepted, Technical Issue

#276 Translation translation omission
  articles/data-factory/v1/data-factory-use-custom-activities.md
Labels: Accepted, Technical Issue

#277 Translation translation omission
  articles/data-factory/v1/data-factory-usql-activity.md
Labels: Accepted, Technical Issue

#278 Translation translation omission
  articles/data-factory/v1/data-factory-web-table-connector.md
Labels: Accepted, Technical Issue

#279 Update alerts-overview.md
  articles/azure-monitor/platform/alerts-overview.md
Labels: Accepted, Linguistic Suggestion

#285 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-oracle-connector.md
Labels: Accepted, Technical Issue

#287 Translation translation omission
  articles/data-factory/v1/data-factory-onprem-sybase-connector.md
Labels: Accepted, Technical Issue

#298 Translation translation omission
  articles/data-factory/tutorial-hybrid-copy-data-tool.md
Labels: Accepted, Technical Issue

#292 Translation translation omission
  articles/data-factory/transform-data-using-hadoop-map-reduce.md
Labels: Accepted, Technical Issue

#306 Translation translation omission
  articles/data-factory/connector-http.md
Labels: Accepted, Technical Issue

#304 Translation translation omission
  articles/data-factory/connector-ftp.md
Labels: Accepted, Technical Issue

#303 Translation translation omission
  articles/data-factory/connector-file-system.md
Labels: Accepted, Technical Issue

#302 Translation translation omission
  articles/data-factory/connector-db2.md
Labels: Accepted, Technical Issue

#301 Translation translation omission
  articles/data-factory/connector-cassandra.md
Labels: Accepted, Technical Issue

#300 Translation translation omission
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, Technical Issue

#299 Translation translation omission
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, Technical Issue

#318 Translation translation omission
  articles/data-factory/connector-sql-server.md
Labels: Accepted, Technical Issue

#317 Translation translation omission
  articles/data-factory/connector-sftp.md
Labels: Accepted, Technical Issue

#316 Translation translation omission
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, Technical Issue

#315 Translation translation omission
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, Technical Issue

#314 Translation translation omission
  articles/data-factory/connector-salesforce.md
Labels: Accepted, Technical Issue

#313 Translation translation omission
  articles/data-factory/connector-postgresql.md
Labels: Accepted, Technical Issue

#312 Translation translation omission
  articles/data-factory/connector-oracle.md
Labels: Accepted, Technical Issue

#311 Translation translation omission
  articles/data-factory/connector-odbc.md
Labels: Accepted, Technical Issue

#310 Translation translation omission
  articles/data-factory/connector-odata.md
Labels: Accepted, Technical Issue

#320 Fix missing
  articles/active-directory-b2c/active-directory-b2c-custom-rest-api-netfw.md
Labels: Accepted, Technical Issue

#329 Fix missing
  articles/azure-functions/functions-bindings-microsoft-graph.md
Labels: In Progress, Linguistic Suggestion

#327 Too much translation
  articles/app-service/overview-local-cache.md
Labels: In Progress, Linguistic Suggestion

#331 Fix missing
  articles/azure-maps/consumption-model.md
Labels: In Progress, Linguistic Suggestion

#333 Fix missing
  articles/azure-maps/extend-geojson.md
Labels: In Progress, Linguistic Suggestion

#341 Fix missing
  articles/cognitive-services/Custom-Vision-Service/csharp-tutorial-od.md
Labels: In Progress, Linguistic Suggestion

#343 Fix missing
  articles/cognitive-services/Custom-Speech-Service/CustomSpeech-How-to-Topics/cognitive-services-custom-speech-subscribe.md
Labels: Accepted, Linguistic Suggestion

#336 Fix missing
  articles/azure-monitor/log-query/examples.md
Labels: Accepted, Linguistic Suggestion

#347 Fix missing
  articles/cognitive-services/LUIS/luis-container-configuration.md
Labels: Accepted, Linguistic Suggestion

#356 Fix missing
  articles/data-factory/connector-odata.md
Labels: Accepted, Linguistic Suggestion
